# steps:
#   - id: "Montando imagem Docker"
#     name: "gcr.io/cloud-builders/docker"
#     args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio_ci:latest", "."]

#   - id: "Compilando Golang"
#     name: "gcr.io/cloud-builders/go"
#     env: ["GOPATH=/go"]
#     args: ["run", "sum"]
steps:
  - id: "Compilando Golang"
    name: "gcr.io/cloud-builders/go"
    args: ["run", "sum"]
    env: ["GOPATH=."]

  - id: "Montando imagem Docker"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio_ci:latest", "."]

images:
  - "gcr.io/$PROJECT_ID/desafio_ci:latest"
