steps:
  - id: "Rodando Teste da aplicação"
    name: "gcr.io/cloud-builders/go"
    args: ["test", "./src/sum"]
    env: ["GOPATH=."]

  - id: "Compilando Golang"
    name: "gcr.io/cloud-builders/go"
    args: ["build", "-o", "./src/sum", "./src/sum"]
    env: ["GOPATH=."]

  - id: "Montando Imagem Docker"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/desafio_ci:latest", "."]

images:
  - "gcr.io/$PROJECT_ID/desafio_ci:latest"
